version: '3'

services:
  postgres:
    image: 'postgres:14'
    container_name: 'freeter-pg'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=db_sb2'

  java_app:
    build: ./
    container_name: 'freeter-app'
    ports:
      - '8082:8080'